version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Set Up CI Environment
          command: |
            mkdir ci_scripts
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" https://api.github.com/repos/6RiverSystems/ci_scripts/contents/ci_tool.sh > ci_scripts/ci_tool.sh
            chmod +x ci_scripts/ci_tool.sh
            ci_scripts/ci_tool.sh --setup_npm
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .

  publish:
    docker:
      - image: node:8.12.0
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run release
          command: |
            ci_scripts/ci_tool.sh --setup_npm
      - run:
          name: npm publish
          command: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: 6rs-circle
      - publish:
          context: 6rs-circle
          requires:
            - build
